# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hgss' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HGSS

  pod 'Eureka',       '~> 2.0.1'

  pod 'Alamofire',    '~> 4.4.0'
  pod 'Unbox',        '~> 2.3.0'
  pod 'Wrap'

end
